### ISSUE TITLE
Heeeeeeeeyyyyy! 

### ISSUE THREAD

**Issue by shaumne** [gooddavvy/DreamLang#1]
I will check it soon!!!!

**Comment by gooddavvy** [comment]
You posted this in the wrong place.

**Comment by gooddavvy** [comment]
It doesn't even have documentation yet, check back in a few days.

**Comment by gooddavvy** [comment]
@shaumne You see DreamPower (it's no longer called DreamLang) is awesome? Please check it's documentation out.

**Comment by gooddavvy** [comment]
> I will check it soon!!!!

**Comment by shaumne** [comment]
> > I will check it soon!!!!
> 
> @shaumne You see DreamPower (it's no longer called DreamLang) is awesome? Please check it's documentation out.

Heyy don't worry just O broke my pc and trying to fix that so... I will looknat it tonight ^^

**Comment by gooddavvy** [comment]
@shaumne You like the language?

**Comment by gooddavvy** [comment]
@shaumne Hello???

**Comment by shaumne** [comment]
> @shaumne Hello???
I apologize, I will look into it as soon as possible. I currently have interviews to attend to, so I am dealing with them.

**Comment by gooddavvy** [comment]
Wow there is always something going on! Interesting! I'll wait for a year for you to see this!

Just kidding

**Comment by gooddavvy** [comment]
> I apologize, I will look into it as soon as possible. I currently have interviews to attend to, so I am dealing with them.

@shaumne You check it out now?

**Comment by gooddavvy** [comment]
@shaumne Hello????????

**Comment by gooddavvy** [comment]
@shaumne You are too slow to respond

**Comment by gooddavvy** [comment]
@shaumne What country are you in? Maybe there are time differences, cause I am in USA

**Comment by shaumne** [comment]
I am in turkey so yes definetly there ara time differences ahahha

**Comment by shaumne** [comment]
And I checked your awesome language and !!!!!!! awesome hahahah
if ;christIsOnEarth {
  print("Jesus Christ is not on Earth.")!
}

**Comment by gooddavvy** [comment]
Thanks! @shaumne Do you have any ideas? And please tell others you know on GitHub to check this out!
